version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  django-ninja:
    build: .
    container_name: api
    command: ["uvicorn", "app.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/db
      - DJANGO_SETTINGS_MODULE=app.settings
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  postgres-data:
    driver: local