# Generated by Django 4.2.11 on 2025-03-02 17:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('month', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('actual', models.FloatField()),
                ('date', models.DateField()),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='month.month')),
            ],
        ),
    ]
