# Generated by Django 4.2.11 on 2025-03-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='savings',
            table='Savings',
        ),
    ]
