# Generated by Django 4.2.11 on 2025-06-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0002_alter_savings_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savings",
            name="actual",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="savings",
            name="budget",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="savings",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="savings",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
