# Generated by Django 4.2.19 on 2025-06-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("month", "0002_alter_month_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="month",
            name="total_income",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="month",
            name="total_savings",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="month",
            name="total_spent",
            field=models.FloatField(null=True),
        ),
    ]
