# Generated by Django 4.2.19 on 2025-06-21 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("month", "0003_month_total_income_month_total_savings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="month",
            name="total_income",
        ),
        migrations.RemoveField(
            model_name="month",
            name="total_savings",
        ),
        migrations.RemoveField(
            model_name="month",
            name="total_spent",
        ),
    ]
