# Generated by Django 4.2.19 on 2025-07-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("month", "0005_month_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="month",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
