# Generated by Django 4.2.19 on 2025-03-02 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id_temp",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.CharField(max_length=4)),
            ],
        ),
    ]
