# Generated by Django 4.2.11 on 2025-03-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('year', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YearData',
            new_name='Year',
        ),
    ]
