# Generated by Django 4.2.19 on 2025-03-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('year', '0002_rename_yeardata_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
