# Generated by Django 4.2.11 on 2025-03-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("year", "0002_rename_id_temp_year_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="year",
            table="Year",
        ),
    ]
