# Generated by Django 4.2.19 on 2025-03-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('year', '0003_alter_year_id_alter_year_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
