# Generated by Django 4.2.19 on 2025-03-02 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('year', '0004_alter_year_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
