# Generated by Django 4.2.19 on 2025-03-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('year', '0005_alter_year_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='id',
            new_name='id_temp',
        ),
    ]
