# Generated by Django 4.2.19 on 2025-03-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='year',
        ),
    ]
