# Generated by Django 4.2.19 on 2025-03-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variable_expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='variableexpense',
            table='Variable Expense',
        ),
    ]
