# Generated by Django 4.2.19 on 2025-03-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variable_expense", "0002_alter_variableexpense_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="variableexpense",
            table="Variable_Expense",
        ),
    ]
