# Generated by Django 4.2.11 on 2025-05-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variable_expense", "0003_alter_variableexpense_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variableexpense",
            name="date",
        ),
    ]
