# Generated by Django 4.2.11 on 2025-05-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable_expense', '0004_remove_variableexpense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableexpense',
            name='actual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='variableexpense',
            name='budget',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='variableexpense',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
