# Generated by Django 4.2.19 on 2025-07-12 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("variable_expense", "0005_alter_variableexpense_actual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variableexpense",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
