# Generated by Django 4.2.19 on 2025-03-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedexpense',
            old_name='date',
            new_name='due',
        ),
    ]
