# Generated by Django 4.2.11 on 2025-06-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixed_expense", "0002_rename_date_fixedexpense_due"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixedexpense",
            name="due",
        ),
        migrations.AddField(
            model_name="fixedexpense",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="fixedexpense",
            name="actual",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="fixedexpense",
            name="budget",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="fixedexpense",
            name="name",
            field=models.CharField(null=True),
        ),
    ]
