# Generated by Django 4.2.19 on 2025-03-30 03:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('month', '0002_alter_month_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('date', models.DateField()),
                ('expected', models.FloatField()),
                ('actual', models.FloatField()),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='month.month')),
            ],
            options={
                'db_table': 'Income',
            },
        ),
    ]
