# Generated by Django 4.2.11 on 2025-06-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="actual",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="expected",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="income",
            name="name",
            field=models.CharField(null=True),
        ),
    ]
